// <auto-generated />
namespace ExpensesProjectMaster.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mileage_inheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mileage_inheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "201610061432399_mileage_inheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
